// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package dal

import (
	"context"
	"fmt"
	"testing"

	"project-layout/internal/model"

	"gorm.io/gen"
	"gorm.io/gen/field"
	"gorm.io/gorm/clause"
)

func init() {
	InitializeDB()
	err := _gen_test_db.AutoMigrate(&model.SysExpress{})
	if err != nil {
		fmt.Printf("Error: AutoMigrate(&model.SysExpress{}) fail: %s", err)
	}
}

func Test_sysExpressQuery(t *testing.T) {
	sysExpress := newSysExpress(_gen_test_db)
	sysExpress = *sysExpress.As(sysExpress.TableName())
	_do := sysExpress.WithContext(context.Background()).Debug()

	primaryKey := field.NewString(sysExpress.TableName(), clause.PrimaryKey)
	_, err := _do.Unscoped().Where(primaryKey.IsNotNull()).Delete()
	if err != nil {
		t.Error("clean table <sys_express> fail:", err)
		return
	}

	_, ok := sysExpress.GetFieldByName("")
	if ok {
		t.Error("GetFieldByName(\"\") from sysExpress success")
	}

	err = _do.Create(&model.SysExpress{})
	if err != nil {
		t.Error("create item in table <sys_express> fail:", err)
	}

	err = _do.Save(&model.SysExpress{})
	if err != nil {
		t.Error("create item in table <sys_express> fail:", err)
	}

	err = _do.CreateInBatches([]*model.SysExpress{{}, {}}, 10)
	if err != nil {
		t.Error("create item in table <sys_express> fail:", err)
	}

	_, err = _do.Select(sysExpress.ALL).Take()
	if err != nil {
		t.Error("Take() on table <sys_express> fail:", err)
	}

	_, err = _do.First()
	if err != nil {
		t.Error("First() on table <sys_express> fail:", err)
	}

	_, err = _do.Last()
	if err != nil {
		t.Error("First() on table <sys_express> fail:", err)
	}

	_, err = _do.Where(primaryKey.IsNotNull()).FindInBatch(10, func(tx gen.Dao, batch int) error { return nil })
	if err != nil {
		t.Error("FindInBatch() on table <sys_express> fail:", err)
	}

	err = _do.Where(primaryKey.IsNotNull()).FindInBatches(&[]*model.SysExpress{}, 10, func(tx gen.Dao, batch int) error { return nil })
	if err != nil {
		t.Error("FindInBatches() on table <sys_express> fail:", err)
	}

	_, err = _do.Select(sysExpress.ALL).Where(primaryKey.IsNotNull()).Order(primaryKey.Desc()).Find()
	if err != nil {
		t.Error("Find() on table <sys_express> fail:", err)
	}

	_, err = _do.Distinct(primaryKey).Take()
	if err != nil {
		t.Error("select Distinct() on table <sys_express> fail:", err)
	}

	_, err = _do.Select(sysExpress.ALL).Omit(primaryKey).Take()
	if err != nil {
		t.Error("Omit() on table <sys_express> fail:", err)
	}

	_, err = _do.Group(primaryKey).Find()
	if err != nil {
		t.Error("Group() on table <sys_express> fail:", err)
	}

	_, err = _do.Scopes(func(dao gen.Dao) gen.Dao { return dao.Where(primaryKey.IsNotNull()) }).Find()
	if err != nil {
		t.Error("Scopes() on table <sys_express> fail:", err)
	}

	_, _, err = _do.FindByPage(0, 1)
	if err != nil {
		t.Error("FindByPage() on table <sys_express> fail:", err)
	}

	_, err = _do.ScanByPage(&model.SysExpress{}, 0, 1)
	if err != nil {
		t.Error("ScanByPage() on table <sys_express> fail:", err)
	}

	_, err = _do.Attrs(primaryKey).Assign(primaryKey).FirstOrInit()
	if err != nil {
		t.Error("FirstOrInit() on table <sys_express> fail:", err)
	}

	_, err = _do.Attrs(primaryKey).Assign(primaryKey).FirstOrCreate()
	if err != nil {
		t.Error("FirstOrCreate() on table <sys_express> fail:", err)
	}

	var _a _another
	var _aPK = field.NewString(_a.TableName(), "id")

	err = _do.Join(&_a, primaryKey.EqCol(_aPK)).Scan(map[string]interface{}{})
	if err != nil {
		t.Error("Join() on table <sys_express> fail:", err)
	}

	err = _do.LeftJoin(&_a, primaryKey.EqCol(_aPK)).Scan(map[string]interface{}{})
	if err != nil {
		t.Error("LeftJoin() on table <sys_express> fail:", err)
	}

	_, err = _do.Not().Or().Clauses().Take()
	if err != nil {
		t.Error("Not/Or/Clauses on table <sys_express> fail:", err)
	}
}
