// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameAdminOperationLog = "admin_operation_log"

// AdminOperationLog mapped from table <admin_operation_log>
type AdminOperationLog struct {
	ID        int64     `gorm:"column:id;primaryKey;autoIncrement:true" json:"id"`
	UserID    int64     `gorm:"column:user_id;not null" json:"user_id"`
	Path      string    `gorm:"column:path;not null" json:"path"`
	Method    string    `gorm:"column:method;not null" json:"method"`
	IP        string    `gorm:"column:ip;not null" json:"ip"`
	Input     string    `gorm:"column:input;not null" json:"input"`
	CreatedAt time.Time `gorm:"column:created_at" json:"created_at"`
	UpdatedAt time.Time `gorm:"column:updated_at" json:"updated_at"`
}

// TableName AdminOperationLog's table name
func (*AdminOperationLog) TableName() string {
	return TableNameAdminOperationLog
}
