// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameAdminExtension = "admin_extensions"

// AdminExtension mapped from table <admin_extensions>
type AdminExtension struct {
	ID        int       `gorm:"column:id;primaryKey;autoIncrement:true" json:"id"`
	Name      string    `gorm:"column:name;not null" json:"name"`
	Version   string    `gorm:"column:version;not null" json:"version"`
	IsEnabled int8      `gorm:"column:is_enabled;not null" json:"is_enabled"`
	Options   string    `gorm:"column:options" json:"options"`
	CreatedAt time.Time `gorm:"column:created_at" json:"created_at"`
	UpdatedAt time.Time `gorm:"column:updated_at" json:"updated_at"`
}

// TableName AdminExtension's table name
func (*AdminExtension) TableName() string {
	return TableNameAdminExtension
}
