// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameAdminMenu = "admin_menu"

// AdminMenu mapped from table <admin_menu>
type AdminMenu struct {
	ID        int64     `gorm:"column:id;primaryKey;autoIncrement:true" json:"id"`
	ParentID  int64     `gorm:"column:parent_id;not null" json:"parent_id"`
	Order_    int       `gorm:"column:order;not null" json:"order"`
	Title     string    `gorm:"column:title;not null" json:"title"`
	Icon      string    `gorm:"column:icon" json:"icon"`
	URI       string    `gorm:"column:uri" json:"uri"`
	Extension string    `gorm:"column:extension;not null" json:"extension"`
	Show      int8      `gorm:"column:show;not null;default:1" json:"show"`
	CreatedAt time.Time `gorm:"column:created_at" json:"created_at"`
	UpdatedAt time.Time `gorm:"column:updated_at" json:"updated_at"`
}

// TableName AdminMenu's table name
func (*AdminMenu) TableName() string {
	return TableNameAdminMenu
}
