// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

const TableNameOmsOrderReturnApply = "oms_order_return_apply"

// OmsOrderReturnApply mapped from table <oms_order_return_apply>
type OmsOrderReturnApply struct {
	ID            int    `gorm:"column:id;primaryKey;autoIncrement:true;comment:ID" json:"id"`      // ID
	OrderID       int64  `gorm:"column:order_id;not null;comment:订单id" json:"order_id"`             // 订单id
	OrderNo       string `gorm:"column:order_no;not null;comment:订单号" json:"order_no"`              // 订单号
	SkuID         int64  `gorm:"column:sku_id;not null;comment:sku_id" json:"sku_id"`               // sku_id
	Username      string `gorm:"column:username;not null;comment:用户名" json:"username"`              // 用户名
	Amount        int64  `gorm:"column:amount;not null;comment:退款金额" json:"amount"`                 // 退款金额
	ReturnName    string `gorm:"column:return_name;not null;comment:退款人姓名" json:"return_name"`      // 退款人姓名
	ReturnPhone   string `gorm:"column:return_phone;not null;comment:退款人手机号" json:"return_phone"`   // 退款人手机号
	Status        int8   `gorm:"column:status;not null;comment:订单状态" json:"status"`                 // 订单状态
	SkuName       string `gorm:"column:sku_name;not null;comment:商品sku名" json:"sku_name"`           // 商品sku名
	SkuImg        string `gorm:"column:sku_img;not null;comment:商品sku图片" json:"sku_img"`            // 商品sku图片
	SkuPrice      int64  `gorm:"column:sku_price;not null;comment:商品单价/分" json:"sku_price"`         // 商品单价/分
	SkuAttrs      string `gorm:"column:sku_attrs;not null;comment:商品销售属性组合（JSON）" json:"sku_attrs"` // 商品销售属性组合（JSON）
	PayAmount     int64  `gorm:"column:pay_amount;not null;comment:支付金额" json:"pay_amount"`         // 支付金额
	SkuNum        int64  `gorm:"column:sku_num;not null;comment:退货数量" json:"sku_num"`               // 退货数量
	SpuBrand      string `gorm:"column:spu_brand;not null;comment:品牌" json:"spu_brand"`             // 品牌
	Reason        string `gorm:"column:reason;not null;comment:原因" json:"reason"`                   // 原因
	Desc          string `gorm:"column:desc;not null;comment:描述" json:"desc"`                       // 描述
	DescPics      string `gorm:"column:desc_pics;not null;comment:凭证图片多个逗号连接" json:"desc_pics"`     // 凭证图片多个逗号连接
	HandleAt      int64  `gorm:"column:handle_at;not null;comment:处理时间" json:"handle_at"`           // 处理时间
	HandleNote    string `gorm:"column:handle_note;not null;comment:处理备注" json:"handle_note"`       // 处理备注
	HandleBy      string `gorm:"column:handle_by;not null;comment:处理人" json:"handle_by"`            // 处理人
	ReceiveName   string `gorm:"column:receive_name;not null;comment:收货人姓名" json:"receive_name"`    // 收货人姓名
	ReceivePhone  string `gorm:"column:receive_phone;not null;comment:收货人手机" json:"receive_phone"`  // 收货人手机
	ReceiveNote   string `gorm:"column:receive_note;not null;comment:收货备注" json:"receive_note"`     // 收货备注
	ReceiveAt     int64  `gorm:"column:receive_at;not null;comment:收货时间" json:"receive_at"`         // 收货时间
	AddressDetail string `gorm:"column:address_detail;not null;comment:收货地址" json:"address_detail"` // 收货地址
	CreatedAt     int    `gorm:"column:created_at;not null;comment:创建时间" json:"created_at"`         // 创建时间
	UpdatedAt     int    `gorm:"column:updated_at;not null;comment:更新时间" json:"updated_at"`         // 更新时间
}

// TableName OmsOrderReturnApply's table name
func (*OmsOrderReturnApply) TableName() string {
	return TableNameOmsOrderReturnApply
}
