// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameOmsOrderBill = "oms_order_bill"

// OmsOrderBill mapped from table <oms_order_bill>
type OmsOrderBill struct {
	ID          int       `gorm:"column:id;primaryKey;autoIncrement:true;comment:ID" json:"id"`                        // ID
	MemberID    int       `gorm:"column:member_id;not null;comment:用户id" json:"member_id"`                             // 用户id
	OrderID     int       `gorm:"column:order_id;not null;comment:订单id" json:"order_id"`                               // 订单id
	Type        int8      `gorm:"column:type;not null;comment:类型：0:个人,1:企业" json:"type"`                               // 类型：0:个人,1:企业
	Name        string    `gorm:"column:name;not null;comment:名称/公司名称" json:"name"`                                    // 名称/公司名称
	Phone       string    `gorm:"column:phone;not null;comment:手机号" json:"phone"`                                      // 手机号
	Email       string    `gorm:"column:email;not null;comment:邮箱" json:"email"`                                       // 邮箱
	Code        string    `gorm:"column:code;not null;comment:税号" json:"code"`                                         // 税号
	Address     string    `gorm:"column:address;not null;comment:地址" json:"address"`                                   // 地址
	BankName    string    `gorm:"column:bank_name;not null;comment:开户行" json:"bank_name"`                              // 开户行
	BankAccount string    `gorm:"column:bank_account;not null;comment:银行账号" json:"bank_account"`                       // 银行账号
	IsFinish    int8      `gorm:"column:is_finish;not null;comment:是否开票" json:"is_finish"`                             // 是否开票
	CreatedAt   time.Time `gorm:"column:created_at;not null;default:CURRENT_TIMESTAMP;comment:创建时间" json:"created_at"` // 创建时间
	UpdatedAt   time.Time `gorm:"column:updated_at;not null;comment:更新时间" json:"updated_at"`                           // 更新时间
}

// TableName OmsOrderBill's table name
func (*OmsOrderBill) TableName() string {
	return TableNameOmsOrderBill
}
