// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

const TableNameOmsPayment = "oms_payment"

// OmsPayment mapped from table <oms_payment>
type OmsPayment struct {
	ID              int    `gorm:"column:id;primaryKey;autoIncrement:true;comment:ID" json:"id"`          // ID
	OrderID         int64  `gorm:"column:order_id;not null;comment:订单id" json:"order_id"`                 // 订单id
	OrderNo         string `gorm:"column:order_no;not null;comment:订单号" json:"order_no"`                  // 订单号
	TradeNo         string `gorm:"column:trade_no;not null;comment:交易号" json:"trade_no"`                  // 交易号
	Amount          int64  `gorm:"column:amount;not null;comment:交易金额/分" json:"amount"`                   // 交易金额/分
	Subject         string `gorm:"column:subject;not null;comment:交易内容" json:"subject"`                   // 交易内容
	ConfirmAt       int64  `gorm:"column:confirm_at;not null;comment:确认时间" json:"confirm_at"`             // 确认时间
	CallbackContent string `gorm:"column:callback_content;not null;comment:回调内容" json:"callback_content"` // 回调内容
	CallbackAt      int64  `gorm:"column:callback_at;not null;comment:回调时间" json:"callback_at"`           // 回调时间
	CreatedAt       int    `gorm:"column:created_at;not null;comment:创建时间" json:"created_at"`             // 创建时间
	UpdatedAt       int    `gorm:"column:updated_at;not null;comment:更新时间" json:"updated_at"`             // 更新时间
}

// TableName OmsPayment's table name
func (*OmsPayment) TableName() string {
	return TableNameOmsPayment
}
