// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"

	"gorm.io/gorm"
)

const TableNamePmsSpu = "pms_spu"

// PmsSpu mapped from table <pms_spu>
type PmsSpu struct {
	ID           int            `gorm:"column:id;primaryKey;autoIncrement:true;comment:ID" json:"id"`                        // ID
	CatID        int            `gorm:"column:cat_id;not null;comment:产品分类" json:"cat_id"`                                   // 产品分类
	BrandID      int            `gorm:"column:brand_id;not null;comment:品牌id" json:"brand_id"`                               // 品牌id
	Name         string         `gorm:"column:name;not null;comment:商品名" json:"name"`                                        // 商品名
	Cover        string         `gorm:"column:cover;not null;comment:封面图" json:"cover"`                                      // 封面图
	OtPrice      int            `gorm:"column:ot_price;not null;comment:市场价" json:"ot_price"`                                // 市场价
	Price        int            `gorm:"column:price;not null;comment:销售价" json:"price"`                                      // 销售价
	Desc         string         `gorm:"column:desc;not null;comment:商品描述" json:"desc"`                                       // 商品描述
	BannerImages string         `gorm:"column:banner_images;not null;comment:轮播图" json:"banner_images"`                      // 轮播图
	Keyword      string         `gorm:"column:keyword;not null;comment:商品关键词" json:"keyword"`                                // 商品关键词
	UnitName     string         `gorm:"column:unit_name;not null;comment:单位名" json:"unit_name"`                              // 单位名
	Video        string         `gorm:"column:video;not null;comment:视频地址" json:"video"`                                     // 视频地址
	Postage      int            `gorm:"column:postage;not null;comment:邮费" json:"postage"`                                   // 邮费
	SaleCount    int            `gorm:"column:sale_count;not null;comment:销量" json:"sale_count"`                             // 销量
	IsMany       int8           `gorm:"column:is_many;not null;comment:是否多规格" json:"is_many"`                                // 是否多规格
	Status       int8           `gorm:"column:status;not null;comment:状态" json:"status"`                                     // 状态
	Sort         int32          `gorm:"column:sort;not null;default:50;comment:排序" json:"sort"`                              // 排序
	CreatedAt    time.Time      `gorm:"column:created_at;not null;default:CURRENT_TIMESTAMP;comment:创建时间" json:"created_at"` // 创建时间
	UpdatedAt    time.Time      `gorm:"column:updated_at;not null;default:CURRENT_TIMESTAMP;comment:更新时间" json:"updated_at"` // 更新时间
	DeletedAt    gorm.DeletedAt `gorm:"column:deleted_at;comment:删除时间" json:"deleted_at"`                                    // 删除时间
}

// TableName PmsSpu's table name
func (*PmsSpu) TableName() string {
	return TableNamePmsSpu
}
