// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

const TableNamePmsSpuDesc = "pms_spu_desc"

// PmsSpuDesc mapped from table <pms_spu_desc>
type PmsSpuDesc struct {
	ID      int    `gorm:"column:id;primaryKey;autoIncrement:true;comment:ID" json:"id"` // ID
	SpuID   int    `gorm:"column:spu_id;not null;comment:spu_id" json:"spu_id"`          // spu_id
	Content string `gorm:"column:content;comment:商品介绍" json:"content"`                   // 商品介绍
}

// TableName PmsSpuDesc's table name
func (*PmsSpuDesc) TableName() string {
	return TableNamePmsSpuDesc
}
