// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

const TableNamePmsSpuInfo = "pms_spu_info"

// PmsSpuInfo mapped from table <pms_spu_info>
type PmsSpuInfo struct {
	ID      int    `gorm:"column:id;primaryKey;autoIncrement:true;comment:ID" json:"id"` // ID
	SpuID   int    `gorm:"column:spu_id;not null;comment:spu_id" json:"spu_id"`          // spu_id
	Content string `gorm:"column:content;comment:商品介绍" json:"content"`                   // 商品介绍
}

// TableName PmsSpuInfo's table name
func (*PmsSpuInfo) TableName() string {
	return TableNamePmsSpuInfo
}
