// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

const TableNamePmsCategoryRelBrand = "pms_category_rel_brand"

// PmsCategoryRelBrand mapped from table <pms_category_rel_brand>
type PmsCategoryRelBrand struct {
	ID      int `gorm:"column:id;primaryKey;autoIncrement:true;comment:ID" json:"id"` // ID
	CatID   int `gorm:"column:cat_id;not null;comment:产品分类" json:"cat_id"`            // 产品分类
	BrandID int `gorm:"column:brand_id;not null;comment:品牌id" json:"brand_id"`        // 品牌id
}

// TableName PmsCategoryRelBrand's table name
func (*PmsCategoryRelBrand) TableName() string {
	return TableNamePmsCategoryRelBrand
}
