// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNamePmsBrand = "pms_brand"

// PmsBrand mapped from table <pms_brand>
type PmsBrand struct {
	ID        int       `gorm:"column:id;primaryKey;autoIncrement:true;comment:ID" json:"id"`                        // ID
	Name      string    `gorm:"column:name;not null;comment:品牌" json:"name"`                                         // 品牌
	Desc      string    `gorm:"column:desc;not null;comment:描述" json:"desc"`                                         // 描述
	Logo      string    `gorm:"column:logo;not null;comment:品牌logo" json:"logo"`                                     // 品牌logo
	Cover     string    `gorm:"column:cover;not null;comment:品牌封面" json:"cover"`                                     // 品牌封面
	IsRelease int8      `gorm:"column:is_release;not null;comment:是否发布上线" json:"is_release"`                         // 是否发布上线
	Sort      int       `gorm:"column:sort;not null;default:50;comment:排序" json:"sort"`                              // 排序
	CreatedAt time.Time `gorm:"column:created_at;not null;default:CURRENT_TIMESTAMP;comment:创建时间" json:"created_at"` // 创建时间
	UpdatedAt time.Time `gorm:"column:updated_at;not null;default:CURRENT_TIMESTAMP;comment:更新时间" json:"updated_at"` // 更新时间
}

// TableName PmsBrand's table name
func (*PmsBrand) TableName() string {
	return TableNamePmsBrand
}
