// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

const TableNamePmsAttrValue = "pms_attr_value"

// PmsAttrValue mapped from table <pms_attr_value>
type PmsAttrValue struct {
	ID        int    `gorm:"column:id;primaryKey;autoIncrement:true;comment:ID" json:"id"` // ID
	SpuID     int    `gorm:"column:spu_id;not null;comment:spu_id" json:"spu_id"`          // spu_id
	AttrID    int    `gorm:"column:attr_id;not null;comment:属性id" json:"attr_id"`          // 属性id
	AttrName  string `gorm:"column:attr_name;not null;comment:属性名" json:"attr_name"`       // 属性名
	AttrValue string `gorm:"column:attr_value;not null;comment:属性值" json:"attr_value"`     // 属性值
	IsShow    int8   `gorm:"column:is_show;not null;comment:是否展示在介绍上" json:"is_show"`      // 是否展示在介绍上
	Sort      int32  `gorm:"column:sort;not null;default:50;comment:排序" json:"sort"`       // 排序
}

// TableName PmsAttrValue's table name
func (*PmsAttrValue) TableName() string {
	return TableNamePmsAttrValue
}
