// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

const TableNameSmsAgreement = "sms_agreement"

// SmsAgreement 平台协议
type SmsAgreement struct {
	ID        int    `gorm:"column:id;primaryKey;autoIncrement:true;comment:自增ID" json:"id"`    // 自增ID
	Title     string `gorm:"column:title;not null;comment:协议名称" json:"title"`                   // 协议名称
	Content   string `gorm:"column:content;comment:协议内容" json:"content"`                        // 协议内容
	Status    bool   `gorm:"column:status;not null;default:1;comment:1：显示：0：不显示" json:"status"` // 1：显示：0：不显示
	CreatedAt int64  `gorm:"column:created_at;not null;comment:添加时间" json:"created_at"`         // 添加时间
}

// TableName SmsAgreement's table name
func (*SmsAgreement) TableName() string {
	return TableNameSmsAgreement
}
