// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

const TableNameSmsSeckillActivity = "sms_seckill_activity"

// SmsSeckillActivity mapped from table <sms_seckill_activity>
type SmsSeckillActivity struct {
	ID        int    `gorm:"column:id;primaryKey;autoIncrement:true;comment:ID" json:"id"` // ID
	Title     string `gorm:"column:title;not null;comment:标题" json:"title"`                // 标题
	Cover     string `gorm:"column:cover;not null;comment:活动封面" json:"cover"`              // 活动封面
	StartAt   int64  `gorm:"column:start_at;not null;comment:开始时间" json:"start_at"`        // 开始时间
	EndAt     int64  `gorm:"column:end_at;not null;comment:结束时间" json:"end_at"`            // 结束时间
	IsRelease int8   `gorm:"column:is_release;not null;comment:是否发布上线" json:"is_release"`  // 是否发布上线
	CreateBy  int    `gorm:"column:create_by;not null;comment:创建者" json:"create_by"`       // 创建者
	UpdateBy  int    `gorm:"column:update_by;not null;comment:更新者" json:"update_by"`       // 更新者
	CreatedAt int    `gorm:"column:created_at;not null;comment:创建时间" json:"created_at"`    // 创建时间
	UpdatedAt int    `gorm:"column:updated_at;not null;comment:更新时间" json:"updated_at"`    // 更新时间
}

// TableName SmsSeckillActivity's table name
func (*SmsSeckillActivity) TableName() string {
	return TableNameSmsSeckillActivity
}
