// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

const TableNameSmsAppVersion = "sms_app_version"

// SmsAppVersion APP版本表
type SmsAppVersion struct {
	ID        int    `gorm:"column:id;primaryKey;autoIncrement:true;comment:自增ID" json:"id"`   // 自增ID
	Version   string `gorm:"column:version;not null;comment:版本号" json:"version"`               // 版本号
	Platform  bool   `gorm:"column:platform;not null;comment:平台类型:1.安卓 2.IOS" json:"platform"` // 平台类型:1.安卓 2.IOS
	Info      string `gorm:"column:info;comment:升级信息" json:"info"`                             // 升级信息
	URL       string `gorm:"column:url;not null;comment:下载链接" json:"url"`                      // 下载链接
	IsForce   bool   `gorm:"column:is_force;not null;comment:是否强制升级" json:"is_force"`          // 是否强制升级
	IsNew     bool   `gorm:"column:is_new;not null;comment:是否最新" json:"is_new"`                // 是否最新
	CreatedAt int64  `gorm:"column:created_at;not null;comment:添加时间" json:"created_at"`        // 添加时间
}

// TableName SmsAppVersion's table name
func (*SmsAppVersion) TableName() string {
	return TableNameSmsAppVersion
}
