// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

const TableNameSmsAppNotice = "sms_app_notice"

// SmsAppNotice mapped from table <sms_app_notice>
type SmsAppNotice struct {
	ID        int    `gorm:"column:id;primaryKey;autoIncrement:true;comment:ID" json:"id"` // ID
	Title     string `gorm:"column:title;not null;comment:标题" json:"title"`                // 标题
	Content   string `gorm:"column:content;not null;comment:内容" json:"content"`            // 内容
	CreateBy  int    `gorm:"column:create_by;not null;comment:创建者" json:"create_by"`       // 创建者
	UpdateBy  int    `gorm:"column:update_by;not null;comment:更新者" json:"update_by"`       // 更新者
	CreatedAt int    `gorm:"column:created_at;not null;comment:创建时间" json:"created_at"`    // 创建时间
	UpdatedAt int    `gorm:"column:updated_at;not null;comment:更新时间" json:"updated_at"`    // 更新时间
}

// TableName SmsAppNotice's table name
func (*SmsAppNotice) TableName() string {
	return TableNameSmsAppNotice
}
