// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

const TableNameSysCityArea = "sys_city_area"

// SysCityArea 省市区县数据
type SysCityArea struct {
	ID       int    `gorm:"column:id;primaryKey;autoIncrement:true" json:"id"`
	Path     string `gorm:"column:path;not null;default:/;comment:省市级别" json:"path"` // 省市级别
	ParentID int64  `gorm:"column:parent_id;not null;comment:父级id" json:"parent_id"` // 父级id
	Type     string `gorm:"column:type;not null;comment:类型" json:"type"`             // 类型
	Name     string `gorm:"column:name;not null;comment:名称" json:"name"`             // 名称
	Level    bool   `gorm:"column:level;not null;comment:级别" json:"level"`           // 级别
	Code     string `gorm:"column:code;not null;comment:城市编码" json:"code"`           // 城市编码
	Snum     int64  `gorm:"column:snum;not null;comment:子级个数" json:"snum"`           // 子级个数
}

// TableName SysCityArea's table name
func (*SysCityArea) TableName() string {
	return TableNameSysCityArea
}
