// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

const TableNameUmsMemberLevel = "ums_member_level"

// UmsMemberLevel mapped from table <ums_member_level>
type UmsMemberLevel struct {
	ID            int    `gorm:"column:id;primaryKey;autoIncrement:true;comment:ID" json:"id"`          // ID
	Name          string `gorm:"column:name;not null;comment:等级名称" json:"name"`                         // 等级名称
	Growth        int64  `gorm:"column:growth;not null;comment:等级需要的成长值" json:"growth"`                 // 等级需要的成长值
	FreeFreight   int64  `gorm:"column:free_freight;not null;comment:免运费标准" json:"free_freight"`        // 免运费标准
	CommentGrowth int64  `gorm:"column:comment_growth;not null;comment:评论获取的成长值" json:"comment_growth"` // 评论获取的成长值
	IsFreight     int8   `gorm:"column:is_freight;not null;comment:是否有免邮特权" json:"is_freight"`          // 是否有免邮特权
	IsMember      int8   `gorm:"column:is_member;not null;comment:是否有会员价格特权" json:"is_member"`          // 是否有会员价格特权
	IsBirthday    int8   `gorm:"column:is_birthday;not null;comment:是否有生日特权" json:"is_birthday"`        // 是否有生日特权
	IsDefault     int8   `gorm:"column:is_default;not null;comment:是否默认等级" json:"is_default"`           // 是否默认等级
	Note          string `gorm:"column:note;not null;comment:备注" json:"note"`                           // 备注
	CreatedAt     int    `gorm:"column:created_at;not null;comment:创建时间" json:"created_at"`             // 创建时间
	UpdatedAt     int    `gorm:"column:updated_at;not null;comment:更新时间" json:"updated_at"`             // 更新时间
}

// TableName UmsMemberLevel's table name
func (*UmsMemberLevel) TableName() string {
	return TableNameUmsMemberLevel
}
