// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameWmsPurchaseDetail = "wms_purchase_detail"

// WmsPurchaseDetail mapped from table <wms_purchase_detail>
type WmsPurchaseDetail struct {
	ID         int       `gorm:"column:id;primaryKey;autoIncrement:true;comment:ID" json:"id"`                        // ID
	PurchaseID int       `gorm:"column:purchase_id;not null;comment:采购单id" json:"purchase_id"`                        // 采购单id
	SkuID      int       `gorm:"column:sku_id;not null;comment:采购商品id" json:"sku_id"`                                 // 采购商品id
	SkuNum     int       `gorm:"column:sku_num;not null;comment:采购数量" json:"sku_num"`                                 // 采购数量
	SkuPrice   int       `gorm:"column:sku_price;not null;comment:采购金额/分" json:"sku_price"`                           // 采购金额/分
	WareID     int       `gorm:"column:ware_id;not null;comment:仓库id" json:"ware_id"`                                 // 仓库id
	Status     int8      `gorm:"column:status;not null;comment:状态[0新建，1已分配，2正在采购，3已完成，4采购失败]" json:"status"`          // 状态[0新建，1已分配，2正在采购，3已完成，4采购失败]
	CreatedAt  time.Time `gorm:"column:created_at;not null;default:CURRENT_TIMESTAMP;comment:创建时间" json:"created_at"` // 创建时间
	UpdatedAt  time.Time `gorm:"column:updated_at;not null;default:CURRENT_TIMESTAMP;comment:更新时间" json:"updated_at"` // 更新时间
}

// TableName WmsPurchaseDetail's table name
func (*WmsPurchaseDetail) TableName() string {
	return TableNameWmsPurchaseDetail
}
